{{- if not .Values.inwx.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cert-manager-webhook-inwx.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "cert-manager-webhook-inwx.name" . }}
    chart: {{ include "cert-manager-webhook-inwx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  username: {{ .Values.inwx.username | quote }}
  password: {{ .Values.inwx.password | quote }}
{{- end }}
